version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - yum install pip -y
      - pip install awscli --upgrade --user

  build:
    commands:
      - mvn clean package deploy
